---
- name: Kamera ve Termal Yazıcı Kontrolü
  hosts: all
  become: true

  tasks:
    - name: Kamera bağlı mı? (v4l2 cihazı)
      stat:
        path: /dev/video0
      register: camera_status

    - name: Kamera durumu
      debug:
        msg: "Kamera bulundu: {{ camera_status.stat.exists }}"

    - name: Termal yazıcı bağlı mı? (CDC ACM USB)
      shell: lsusb | grep -i 'CDC' || true
      register: printer_result

    - name: Termal yazıcı çıktısı
      debug:
        var: printer_result.stdout_lines

    - name: /dev/ttyACM0 var mı?
      stat:
        path: /dev/ttyACM0
      register: acm_check

    - name: Termal yazıcı port kontrol
      debug:
        msg: "Termal yazıcı portu mevcut: {{ acm_check.stat.exists }}"
