---
- name: Sistem Zamanı ve Ağ Kontrolü
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: 🕒 Sistem zamanı kontrol
      command: timedatectl
      register: time_output

    - name: Zaman çıktısını yazdır
      debug:
        var: time_output.stdout_lines

    - name: 🔁 NTP senkronizasyon durumu
      shell: timedatectl show -p NTPSynchronized --value
      register: ntp_sync

    - name: NTP senkronizasyon sonucu
      debug:
        msg: "NTP senkronizasyonu: {{ ntp_sync.stdout }}"

    - name: 🌐 Google DNS’e ping at (internet bağlantı kontrolü)
      command: ping -c 3 8.8.8.8
      register: ping_result
      ignore_errors: true

    - name: Ping sonucu
      debug:
        var: ping_result.stdout_lines

    - name: 🛠 RTC yerel saat olarak ayarlı mı? (uyarı varsa düzelt)
      command: timedatectl set-local-rtc 0 --adjust-system-clock
      when: "'RTC in local TZ: yes' in time_output.stdout"
