- name: Update & upgrade packages
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
