---
- name: Sistemi Güncelle
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Sistemi güncelle
      shell: |
        unset HISTFILE
        sudo apt-get update -y
        sudo apt-get install -f -y
        sudo apt-get --fix-broken install -y
        sudo apt-get upgrade -y
        sudo apt-get full-upgrade -y
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
