---
- name: Sistemi Güncelle
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Sistemi güncelle
      shell: |
        unset HISTFILE
        apt-get update -y
        apt-get install -f -y
        apt-get --fix-broken install -y
        apt-get upgrade -y
        apt-get full-upgrade -y
        apt-get autoremove -y
        apt-get autoclean -y
      args:
        executable: /bin/bash
