- name: Update & upgrade packages
  hosts: all
  tasks:
    - name: Update package list
      become: true
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: true
      apt:
        upgrade: dist
