# update.yml
---
- name: Cihazları Güncelle
  hosts: all
  become: yes
  tasks:
    - name: Sistemi Güncelle
      shell: |
        unset HISTFILE
        apt-get update
        apt-get install -f -y
        apt-get --fix-broken install -y
        apt-get upgrade -y
        apt-get full-upgrade -y
        apt-get autoremove -y
        apt-get autoclean
      args:
        executable: /bin/bash
